FROM almalinux:latest
LABEL maintainer="Karthikeyan Elangovan"

ENV SPLUNK_HOME=/opt/splunkforwarder \
    SPLUNK_GROUP=splunk \
    SPLUNK_USER=splunk

USER root
ENV http_proxy http://10.143.0.177:8080
ENV https_proxy http://10.143.0.177:8080

# Install required dependencies
#RUN dnf update -y

#RUN dnf install wget -y

# Download the Splunk Universal Forwarder RPM
COPY ["splunkforwarder-9.0.0-6818ac46f2ec-linux-2.6-x86_64.rpm", "/tmp/splunkforwarder.rpm"]

#RUN wget -O /tmp/splunkforwarder.rpm 'https://www.splunk.com/bin/splunk/DownloadActivityServlet?architecture=x86_64&platform=linux&version=8.3.3&product=universalforwarder&filename=splunkforwarder-8.3.3-63079c59e632-linux-2.6-amd64.rpm&wget=true'

# Install the Splunk Universal Forwarder RPM
RUN dnf install -y /tmp/splunkforwarder.rpm

# Cleanup temporary files
RUN rm -f /tmp/splunkforwarder.rpm

RUN chgrp -R 0 ${SPLUNK_HOME} && chmod -R g+rwx ${SPLUNK_HOME}
RUN ls -lah ${SPLUNK_HOME}

WORKDIR ${SPLUNK_HOME}

#RUN ${SPLUNK_HOME}/bin/splunk start --accept-license --no-prompt --answer-yes --seed-passwd ${SPLUNK_PASSWORD}"

ENTRYPOINT ["/bin/bash", "-c", "${SPLUNK_HOME}/bin/splunk start --accept-license  --answer-yes --no-prompt && tail -f > /dev/null"]
