FROM splunk/universalforwarder:8.2.10
LABEL maintainer="Karthikeyan Elangovan"

USER root
RUN chgrp -R 0 /opt && chmod -R g+rwx /opt
RUN chgrp -R 0 /home/ansible && chmod -R g+rwx /home/ansbile
RUN ls -lah /home/ansible
RUN chgrp -R 0 /hom/ansible/.ansible && chmod -R g+rwx /home/ansible
