FROM alpine:latest
LABEL maintainer="Karthikeyan Elangovan"

ENV SPLUNK_HOME=/opt/splunkforwarder \
    SPLUNK_GROUP=splunk \
    SPLUNK_USER=splunk

# Install required dependencies
RUN apk update && apk add wget rpm

# Download the Splunk Universal Forwarder RPM
COPY ["splunkforwarder-9.0.0-6818ac46f2ec-linux-2.6-x86_64.rpm", "/tmp/splunkforwarder.rpm"]

#RUN wget -O /tmp/splunkforwarder.rpm 'https://www.splunk.com/bin/splunk/DownloadActivityServlet?architecture=x86_64&platform=linux&version=8.3.3&product=universalforwarder&filename=splunkforwarder-8.3.3-63079c59e632-linux-2.6-amd64.rpm&wget=true'

# Install the Splunk Universal Forwarder RPM
RUN rpm -i /tmp/splunkforwarder.rpm

# Cleanup temporary files
RUN rm -f /tmp/splunkforwarder.rpm

# Start the Splunk Universal Forwarder service
CMD ["/opt/splunkforwarder/bin/splunk", "start", "--accept-license", "--no-prompt"]

